version: '3'
services:
  processor:
    image: processor:latest
    container_name: processor
    environment:
      MINIO_ENDPOINT: minio:9000 
    networks:
      - application_network 
    volumes:
      - ../mount_folder/fetched:/app/processing/crawler/fetched
      - ../mount_folder/agg:/app/processing/processor/agg
      - ../mount_folder/joined:/app/processing/processor/joined

networks:
  application_network:
    external: true
