version: "3"
services:
  minio:
    image: docker.arvancloud.ir/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    env_file:
      - ./minio-secrets.env
    command: server /data
    volumes:
      - ./data:/data
    networks:
      - application_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  application_network:
    external: true
